### ISSUE TITLE
help in visual studio

### ISSUE THREAD

**Issue by Roizor** [TFTWPhoenix/IonOS#1]
Building solution IonOS (Debug)
Build started 9/14/2020 2:21:34 PM.
__________________________________________________
Project "/Users/aidensanchez/Desktop/IonOS-master/IonOS.csproj" (Build target(s)):

Target ResolvePackageAssets:
    /Users/aidensanchez/Desktop/IonOS-master/IonOS.csproj : error NU1101: Unable to find package Cosmos.Debug.Kernel. No packages exist with this id in source(s): nuget.org
    /Users/aidensanchez/Desktop/IonOS-master/IonOS.csproj : error NU1101: Unable to find package Cosmos.Build. No packages exist with this id in source(s): nuget.org
    /Users/aidensanchez/Desktop/IonOS-master/IonOS.csproj : error NU1101: Unable to find package Cosmos.System2. No packages exist with this id in source(s): nuget.org
    /Users/aidensanchez/Desktop/IonOS-master/IonOS.csproj : error : NETSDK1056: Project is targeting runtime 'cosmos' but did not resolve any runtime-specific packages. This runtime may not be supported by the target framework.
Done building target "ResolvePackageAssets" in project "IonOS.csproj" -- FAILED.

Done building project "IonOS.csproj" -- FAILED.

Build FAILED.

/Users/aidensanchez/Desktop/IonOS-master/IonOS.csproj : error NU1101: Unable to find package Cosmos.Debug.Kernel. No packages exist with this id in source(s): nuget.org
/Users/aidensanchez/Desktop/IonOS-master/IonOS.csproj : error NU1101: Unable to find package Cosmos.Build. No packages exist with this id in source(s): nuget.org
/Users/aidensanchez/Desktop/IonOS-master/IonOS.csproj : error NU1101: Unable to find package Cosmos.System2. No packages exist with this id in source(s): nuget.org
/Users/aidensanchez/Desktop/IonOS-master/IonOS.csproj : error : NETSDK1056: Project is targeting runtime 'cosmos' but did not resolve any runtime-specific packages. This runtime may not be supported by the target framework.
    0 Warning(s)
    4 Error(s)

Time Elapsed 00:00:00.06

========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Build: 4 errors, 0 warnings

no Cosmos lib?

**Comment by TFTWPhoenix** [comment]
@Roizor you must download and install the Cosmos User Kit.

**Comment by TFTWPhoenix** [comment]
Actually I'll leave this open if you need further assistance.

**Comment by Roizor** [comment]
oh, thanks
